In [1]:
# import sys
# print(sys.executable)
# print(sys.version)

import os
os.environ['PROJ_LIB'] = '/home/jlee/.conda/envs/mmc_sgp/share/proj'

import wrf
from netCDF4 import Dataset
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.cm import get_cmap
from mpl_toolkits.basemap import Basemap
import numpy as np
import pandas as pd
import xarray as xr
from numba import njit

wrf_runs_dir = '/projects/mmc/jlee/sgp/wrf-mmc/wrf-runs/'
nb_dir = !pwd
data_dir_df = pd.read_csv(nb_dir[0]+'/data-dir-j3leswrf.csv', index_col=0)
plots_dir = nb_dir[0]+'/plots_04e'

# get specific dates associated w/ wrf runs
data_dir_df = pd.read_csv(nb_dir[0]+'/data-dir-j3leswrf.csv', index_col=0)

runs_list = list(data_dir_df.index)[:-1]

In [2]:
data_dir_df

2018-08-05     2018-09-01
mynn                           l1_0805m   o1_0901m_30s
mynn_ck0.1                  l7_0805m-ck            NaN
edmf                           l2_0805e   o2_0901e_30s
mynn_all4d-1arcs-topo          l5_0805m            NaN
mynn_d12-9s_d34-1s     n1_d12-9s_d34-1s  o5_0901m_9s1s
mynn_d123-9s_d4-1s_lu  n2_d123-9s_d4-1s            NaN
mynn_all4d-9arcs_lu               n3_9s            NaN
edmf_d12-9s_d34-1s                  NaN  o6_0901e_9s1s
wrf_start                  8/4/18 12:00  8/31/18 12:00

In [3]:
eval_date = '2018-09-01'
run = 'edmf'

date_col = data_dir_df[eval_date]
    
hr = 20

for ind, hr in enumerate(np.arange(16, 24, 1)): 

    file = wrf_runs_dir+date_col[run]+'/auxout/mmc_d02_'+eval_date+'_'+str(hr)+':00:00'
    wrf_single = Dataset(file, 'r')

    var = wrf.getvar(wrf_single, 'EDMF_W', timeidx=wrf.ALL_TIMES)

    # d04 grid cells in d02
    var_w = var[:, :, 121:126, 119:123]
    
#     print(hr,'UTC')
    
    for t in np.arange(0, 6): 
        if (var_w[t, 16, :, :] != 0).sum().values != 0:
            print(var_w[t, :, :, :].Time.values)
            print((var_w[t, 16, :, :] != 0).sum().values)

2018-09-01T17:00:00.000000000
3
2018-09-01T17:10:00.000000000
6
2018-09-01T17:20:00.000000000
6


In [212]:
eval_date = '2018-09-01'
run = 'edmf_d12-9s_d34-1s'

date_col = data_dir_df[eval_date]
    
hr = 20

for ind, hr in enumerate(np.arange(16, 24, 1)): 

    file = wrf_runs_dir+date_col[run]+'/auxout/mmc_d02_'+eval_date+'_'+str(hr)+':00:00'
    wrf_single = Dataset(file, 'r')

    var = wrf.getvar(wrf_single, 'EDMF_W', timeidx=wrf.ALL_TIMES)

    # d04 grid cells in d02
    var_w = var[:, :, 121:126, 119:123]
    
#     print(hr,'UTC')
    
    for t in np.arange(0, 6): 
        if (var_w[t, 16, :, :] != 0).sum().values != 0:
            print(var_w[t, :, :, :].Time.values)
            print((var_w[t, 16, :, :] != 0).sum().values)

2018-09-01T16:00:00.000000000
1
2018-09-01T16:10:00.000000000
1
2018-09-01T16:20:00.000000000
3
2018-09-01T16:30:00.000000000
2
2018-09-01T16:40:00.000000000
1
2018-09-01T16:50:00.000000000
2
2018-09-01T17:00:00.000000000
1


In [199]:
eval_date = '2018-09-01'
run = 'edmf_d12-9s_d34-1s'

date_col = data_dir_df[eval_date]
    
hr = 20

for ind, hr in enumerate(np.arange(16, 24, 1)): 

    file = wrf_runs_dir+date_col[run]+'/auxout/mmc_d02_'+eval_date+'_'+str(hr)+':00:00'
    wrf_single = Dataset(file, 'r')

    var = wrf.getvar(wrf_single, 'EDMF_A', timeidx=wrf.ALL_TIMES)

    # d04 grid cells in d02
    var_w = var[:, :, 121:126, 119:123]
    
    print(hr,'UTC')
    print((var_w[:, 20, :, :] != 0).sum().values)

16 UTC
10
17 UTC
1
18 UTC
0
19 UTC
0
20 UTC
0
21 UTC
0
22 UTC
0
23 UTC
0


In [197]:
eval_date = '2018-09-01'
run = 'edmf_d12-9s_d34-1s'

date_col = data_dir_df[eval_date]
    
hr = 20

for ind, hr in enumerate(np.arange(16, 24, 1)): 

    file = wrf_runs_dir+date_col[run]+'/auxout/mmc_d02_'+eval_date+'_'+str(hr)+':00:00'
    wrf_single = Dataset(file, 'r')

    var = wrf.getvar(wrf_single, 'EDMF_A', timeidx=wrf.ALL_TIMES)

    # d04 grid cells in d02
    var_w = var[:, :, 121:126, 119:123]
    
    print(hr,'UTC')
    print((var_w[:, 16, :, :] != 0).sum().values)

16 UTC
10
17 UTC
1
18 UTC
0
19 UTC
0
20 UTC
0
21 UTC
0
22 UTC
0
23 UTC
0


In [205]:
var_w[1, :, :, :].Time.values

numpy.datetime64('2018-09-01T23:10:00.000000000')

In [22]:
var.XLAT[115:133, :]

<xarray.DataArray 'XLAT' (south_north: 18, west_east: 220)>
array([[36.28063 , 36.28176 , 36.28287 , ..., 36.306057, 36.305145,
        36.30422 ],
       [36.307575, 36.308716, 36.309837, ..., 36.33302 , 36.33212 ,
        36.331192],
       [36.334534, 36.33567 , 36.3368  , ..., 36.35998 , 36.359074,
        36.358162],
       ...,
       [36.68502 , 36.68616 , 36.687286, ..., 36.71058 , 36.709663,
        36.70874 ],
       [36.71198 , 36.71311 , 36.714245, ..., 36.737553, 36.736637,
        36.735714],
       [36.738937, 36.740078, 36.741203, ..., 36.76451 , 36.7636  ,
        36.762676]], dtype=float32)
Coordinates:
    XLONG    (south_north, west_east) float32 -101.5 -101.5 ... -94.22 -94.18
    XLAT     (south_north, west_east) float32 36.28 36.28 36.28 ... 36.76 36.76
Dimensions without coordinates: south_north, west_east

In [8]:
var

<xarray.DataArray 'EDMF_W' (Time: 6, bottom_top: 108, south_north: 220, west_east: 220)>
array([[[[0.        , 0.        , 0.24901947, ..., 0.        ,
          0.        , 0.        ],
         [0.24901946, 0.24901944, 0.        , ..., 0.        ,
          0.21707347, 0.        ],
         [0.24901947, 0.24901947, 0.24901946, ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.24901944, ..., 0.        ,
          0.        , 0.        ],
         [0.06113675, 0.07132042, 0.        , ..., 0.        ,
          0.        , 0.        ]],

        [[0.        , 0.        , 0.27806658, ..., 0.        ,
          0.        , 0.        ],
         [0.2778025 , 0.27746004, 0.        , ..., 0.        ,
          0.24092576, 0.        ],
         [0.27774593, 0.27741912, 0.2776133 , ..., 0.        ,
          0.        , 0.        ],
...
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]],

        [[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]]]], dtype=float32)
Coordinates:
    XLONG    (south_north, west_east) float32 -101.4 -101.3 ... -94.12 -94.08
    XLAT     (south_north, west_east) float32 33.18 33.18 33.18 ... 39.11 39.11
    XTIME    (Time) float32 1.8e+03 1.81e+03 1.82e+03 1.83e+03 1.84e+03 1.85e+03
  * Time     (Time) datetime64[ns] 2018-09-01T18:00:00 ... 2018-09-01T18:50:00
Dimensions without coordinates: bottom_top, south_north, west_east
Attributes:
    FieldType:    104
    MemoryOrder:  XYZ
    description:  EDMF vertical velocity  - mean moist updrafts
    units:        m s-1
    stagger:      
    coordinates:  XLONG XLAT XTIME
    projection:   LambertConformal(stand_lon=-97.48758697509766, moad_cen_lat...

In [9]:
filed4 = wrf_runs_dir+date_col[run]+'/auxout/mmc_d04_'+eval_date+'_'+str(hr)+':00:00'
wrf_singled4 = Dataset(filed4, 'r')

In [11]:
hfxd4 = wrf.getvar(wrf_singled4, 'HFX', timeidx=wrf.ALL_TIMES)

In [15]:
hfxd4.XLAT.max(), hfxd4.XLAT.min()

(<xarray.DataArray 'XLAT' ()>
 array(36.62898254),
 <xarray.DataArray 'XLAT' ()>
 array(36.51060104))

In [16]:
hfxd4.XLONG.max(), hfxd4.XLONG.min()

(<xarray.DataArray 'XLONG' ()>
 array(-97.44958496),
 <xarray.DataArray 'XLONG' ()>
 array(-97.53878784))

In [91]:
filed3 = wrf_runs_dir+date_col[run]+'/auxout/mmc_d03_'+eval_date+'_'+str(hr)+':00:00'
wrf_singled3 = Dataset(filed3, 'r')

hfxd3 = wrf.getvar(wrf_singled3, 'HFX', timeidx=wrf.ALL_TIMES)[:, 158:223, 89:129]

In [92]:
hfxd3.XLAT.max(), hfxd3.XLAT.min()

(<xarray.DataArray 'XLAT' ()>
 array(36.6282692),
 <xarray.DataArray 'XLAT' ()>
 array(36.51312256))

In [93]:
hfxd3.XLONG.max(), hfxd3.XLONG.min()

(<xarray.DataArray 'XLONG' ()>
 array(-97.45046997),
 <xarray.DataArray 'XLONG' ()>
 array(-97.53787231))

In [134]:
var_w = var[:, :, 122:126, 119:123]

In [135]:
var_w.XLAT.max(), var_w.XLAT.min()

(<xarray.DataArray 'XLAT' ()>
 array(36.61926651),
 <xarray.DataArray 'XLAT' ()>
 array(36.53829193))

In [136]:
var_w.XLONG.max(), var_w.XLONG.min()

(<xarray.DataArray 'XLONG' ()>
 array(-97.45269775),
 <xarray.DataArray 'XLONG' ()>
 array(-97.55358887))

In [165]:
var_w = var[:, :, 121:126, 119:123]

In [166]:
var_w.XLAT.max(), var_w.XLAT.min()

(<xarray.DataArray 'XLAT' ()>
 array(36.61926651),
 <xarray.DataArray 'XLAT' ()>
 array(36.51131058))

In [167]:
var_w.XLONG.max(), var_w.XLONG.min()

(<xarray.DataArray 'XLONG' ()>
 array(-97.45269775),
 <xarray.DataArray 'XLONG' ()>
 array(-97.55358887))

In [169]:
var_w[:, 0, :, :]

<xarray.DataArray 'EDMF_W' (Time: 6, south_north: 5, west_east: 4)>
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)
Coordinates:
    XLONG    (south_north, west_east) float32 -97.55 -97.52 ... -97.49 -97.45
    XLAT     (south_north, west_east) float32 36.51 36.51 36.51 ... 36.62 36.62
    XTIME    (Time) float32 1.8e+03 1.81e+03 1.82e+03 1.83e+03 1.84e+03 1.85e+03
  * Time     (Time) datetime64[ns] 2018-09-01T18:00:00 ... 2018-09-01T18:50:00
Dimensions without coordinates: south_north, west_east
Attributes:
    FieldType:    104
    MemoryOrder:  XYZ
    description:  EDMF vertical velocity  - mean moist updrafts
    units:        m s-1
    stagger:      
    coordinates:  XLONG XLAT XTIME
    projection:   LambertConformal(stand_lon=-97.48758697509766, moad_cen_lat...